<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="1" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="OpenWorld_Suite" duration-ms="13480" started-at="2018-07-27T09:12:39Z" finished-at="2018-07-27T09:12:53Z">
    <groups>
    </groups>
    <test name="OpenWorld_Test" duration-ms="13480" started-at="2018-07-27T09:12:39Z" finished-at="2018-07-27T09:12:53Z">
      <class name="TestReport.Login_Test">
        <test-method status="PASS" signature="beforeTest(java.lang.String, java.lang.String)[pri:0, instance:TestReport.Login_Test@ae45eb6]" name="beforeTest" is-config="true" duration-ms="190" started-at="2018-07-27T14:42:39Z" finished-at="2018-07-27T14:42:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[TestReport]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[LoginPage]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="beforeMethod(java.lang.String)[pri:0, instance:TestReport.Login_Test@ae45eb6]" name="beforeMethod" is-config="true" duration-ms="1931" started-at="2018-07-27T14:42:39Z" finished-at="2018-07-27T14:42:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="Test1()[pri:0, instance:TestReport.Login_Test@ae45eb6]" name="Test1" duration-ms="10046" started-at="2018-07-27T14:42:41Z" finished-at="2018-07-27T14:42:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login page not opened expected [1] but found [0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login page not opened expected [1] but found [0]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at TestReport.Login_Test.Test1(Login_Test.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test1 -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:TestReport.Login_Test@ae45eb6]" name="afterMethod" is-config="true" duration-ms="825" started-at="2018-07-27T14:42:51Z" finished-at="2018-07-27T14:42:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Test1 status=FAILURE method=Login_Test.Test1()[pri:0, instance:TestReport.Login_Test@ae45eb6] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="SKIP" signature="Test2()[pri:0, instance:TestReport.Login_Test@ae45eb6]" name="Test2" duration-ms="1" started-at="2018-07-27T14:42:52Z" depends-on-methods="TestReport.Login_Test.Test1" finished-at="2018-07-27T14:42:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test2 -->
        <test-method status="SKIP" signature="Test3()[pri:0, instance:TestReport.Login_Test@ae45eb6]" name="Test3" duration-ms="2" started-at="2018-07-27T14:42:52Z" depends-on-methods="TestReport.Login_Test.Test1" finished-at="2018-07-27T14:42:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test3 -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:TestReport.Login_Test@ae45eb6]" name="afterTest" is-config="true" duration-ms="452" started-at="2018-07-27T14:42:52Z" finished-at="2018-07-27T14:42:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- TestReport.Login_Test -->
    </test> <!-- OpenWorld_Test -->
  </suite> <!-- OpenWorld_Suite -->
</testng-results>
